###############################################################################
# Project Information
################################################################################

site_name: Getty
site_description: A (de)serialization framework for Zig
site_url: https://getty.so/

repo_name: getty-zig/getty
repo_url: https://github.com/getty-zig/getty
edit_uri: https://github.com/getty-zig/getty.so/edit/main/docs/

copyright: © 2022 Getty

################################################################################
# Theme
################################################################################

theme:
  name: material
  font:
    text: Heebo

  icon:
    logo: material/circle-multiple
  favicon: assets/images/getty-favicon-solid-large.png

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    # Enables blog.
    - blog

    # Enables tooltips.
    - content.tooltips

    # Enables code annotations.
    - content.code.annotate

    # Enables code copying.
    - content.code.copy

    # Enables navigation footer.
    - navigation.footer

    # Clicks on internal links won't fully reload the page.
    - navigation.instant

    # Enables sections to have documents attached to them.
    - navigation.indexes

    # Enables tabs in the top bar.
    - navigation.tabs

    # Back to Top button.
    - navigation.top

    # Automatically scroll ToC.
    - toc.follow

    # Enable search suggestions.
    - search.suggest

################################################################################
# Extra
################################################################################

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/ibokuri/
    - icon: fontawesome/brands/discord
      link: https://discord.gg/njDA67U5ph/
  
extra_css:
  - stylesheets/extra.css

################################################################################
# Plugins
################################################################################

plugins:
  # Enables front matter to be set per folder.
  - meta

  # Enables search.
  - search

  # Preserves HTML formatting in navigation and table of contents.
  - typeset


################################################################################
# Extensions
################################################################################

markdown_extensions:
  # Enables tooltips.
  - abbr

  # Enables call-outs.
  - admonition

  # Enables annotations.
  - attr_list

  # Enables definition lists.
  - def_list

  # Enables Markdown inside of HTML.
  - md_in_html

  # Enables superscripts.
  - pymdownx.caret

  # Eanbles call-outs to be collapsible.
  - pymdownx.details

  # Enables icons and Emojis.
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  # Adds support for syntax highlighting.
  - pymdownx.highlight:
      anchor_linenums: true

  # Adds support for inline syntax highlighting.
  - pymdownx.inlinehilite

  # Enables text hightlighting.
  - pymdownx.mark

  # Enables snippets.
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md

  # Enables arbitrary nesting of code and content blocks.
  - pymdownx.superfences

  # Enables subscripts.
  - pymdownx.tilde

  # Enables content tabs.
  - pymdownx.tabbed:
      alternate_style: true

  # Enables task lists.
  - pymdownx.tasklist:
      custom_checkbox: true

  # Enables tables.
  - tables

################################################################################
# Documentation Layout
################################################################################

nav:
  - Home:
    - index.md
  - User Guide:
    - user-guide/index.md
    - user-guide/installation.md
    - Tutorial:
      - user-guide/tutorial/index.md
      - user-guide/tutorial/setup.md
      - user-guide/tutorial/serializers.md
      - user-guide/tutorial/deserializers.md
      - user-guide/tutorial/customization.md
    - Design:
      - user-guide/design/index.md
      - user-guide/design/architecture.md
      - user-guide/design/values.md
      - user-guide/design/data-models.md
      - user-guide/design/interfaces.md
      - user-guide/design/blocks-and-tuples.md
  - Contributing:
    - contributing/index.md
    - contributing/style-guide.md
  - API Reference:
    - https://docs.getty.so/
  #- Blog:
    #- blog/index.md
