###############################################################################
# Project Information
################################################################################

site_name: Getty
site_description: A (de)serialization framework for Zig
site_url: https://getty.so/

repo_name: getty-zig/getty
repo_url: https://github.com/getty-zig/getty
edit_uri: https://github.com/getty-zig/getty.so/edit/main/docs/

copyright: © 2023 Jason Phan

################################################################################
# Theme
################################################################################

theme:
  name: material
  font:
    text: Fira Sans

  icon:
    logo: material/circle-multiple
    repo: fontawesome/brands/github

  favicon: assets/images/getty-favicon-solid-large.png

  palette:
      media: "(prefers-color-scheme: dark)"
      scheme: slate

  custom_dir: docs/overrides

  features:
    # Enables tooltips.
    - content.tooltips

    # Enables code annotations.
    - content.code.annotate

    # Enables code copying.
    - content.code.copy

    # Enables navigation footer.
    - navigation.footer

    # Clicks on internal links won't fully reload the page.
    - navigation.instant

    # Enables sections to have documents attached to them.
    - navigation.indexes

    # Enables tabs in the top bar.
    - navigation.tabs

    # Back to Top button.
    - navigation.top

    # Automatically scroll ToC.
    - toc.follow

    # Enable search suggestions.
    - search.suggest

################################################################################
# Extra
################################################################################

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/getty-zig
    - icon: fontawesome/brands/discord
      link: https://discord.gg/njDA67U5ph
  
extra_css:
  - stylesheets/extra.css

################################################################################
# Plugins
################################################################################

plugins:
  # Enables blog
  - blog:
      blog_dir: blog/
      post_readtime: false
      archive: false
      categories: false
      post_url_format: "{slug}"

      # For some reasion, 'paginate: false' doesn't work, so we'll just set the
      # pagination to a ridiculous number.
      pagination_per_page: 999

  # Enables search.
  - search


################################################################################
# Extensions
################################################################################

markdown_extensions:
  # Enables tooltips.
  - abbr

  # Enables call-outs.
  - admonition

  # Enables annotations.
  - attr_list

  # Enables definition lists.
  - def_list

  # Enables Markdown inside of HTML.
  - md_in_html

  # Enables superscripts.
  - pymdownx.caret

  # Eanbles call-outs to be collapsible.
  - pymdownx.details

  # Enables icons and Emojis.
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  # Adds support for syntax highlighting.
  - pymdownx.highlight:
      anchor_linenums: true

  # Adds support for inline syntax highlighting.
  - pymdownx.inlinehilite

  # Enables text hightlighting.
  - pymdownx.mark

  # Enables snippets.
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md

  # Enables arbitrary nesting of code and content blocks.
  - pymdownx.superfences

  # Enables subscripts.
  - pymdownx.tilde

  # Enables content tabs.
  - pymdownx.tabbed:
      alternate_style: true

  # Enables task lists.
  - pymdownx.tasklist:
      custom_checkbox: true

  # Enables tables.
  - tables

################################################################################
# Documentation Layout
################################################################################

nav:
  - Home:
    - index.md
  - User Guide:
    - user-guide/index.md
    - Tutorial:
      - user-guide/tutorial/index.md
      - user-guide/tutorial/setup.md
      - user-guide/tutorial/interfaces.md
      - user-guide/tutorial/serializers.md
      - user-guide/tutorial/deserializers.md
      - user-guide/tutorial/customization.md
    - user-guide/installation.md
    - Design:
      - user-guide/design/index.md
      - user-guide/design/architecture.md
      - user-guide/design/values.md
      - user-guide/design/data-models.md
      - user-guide/design/blocks-and-tuples.md
  - Blog:
    - blog/index.md
  - Contributing:
    - contributing/index.md
  - API Reference:
    - https://docs.getty.so/
