name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Deploy to docs branch
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - uses: actions/checkout@v3

      - name: Build
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
        run:
        - pip install git+https://${MKDOCS_INSIDERS_TOKEN}@github.com/ibokuri/mkdocs-material-insiders.git
        - mkdocs build --site-dir public

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: docs
          FOLDER: public
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

env:
  MKDOCS_INSIDERS_TOKEN: ${{ secrets.MKDOCS_INSIDERS_TOKEN }}
