name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Deploy to docs branch
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - uses: actions/checkout@v3

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.MKDOCS_MATERIAL_INSIDERS_KEY }}

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: eval `ssh-agent -s` && ssh-add - <<< '${{ secrets.MKDOCS_MATERIAL_INSIDERS_KEY }}'
      - run: pip install git+ssh://git@github.com/ibokuri/mkdocs-material-insiders.git
      - run: mkdocs build --site-dir public

      - uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: docs
          FOLDER: public
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
